version: "3.7"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

services:

  sagas:
    image: "kevinrutherford/rookery-sagas:local-dev"
    build:
      context: ${ROOKERY_SAGAS_REPO}
      dockerfile: dev.Dockerfile
    volumes:
      - ${ROOKERY_SAGAS_REPO}/src:/srv/app/src
    environment:
      - USER_CRB_ID=${USER_CRB_ID}
    depends_on:
      - commands
      - views
    restart: no
    tty: true
    logging: *default-logging

  commands:
    image: "kevinrutherford/rookery-commands:local-dev"
    build:
      context: ${ROOKERY_COMMANDS_REPO}
      dockerfile: dev.Dockerfile
    volumes:
      - ${ROOKERY_COMMANDS_REPO}/src:/srv/app/src
    environment:
      - DEVELOPMENT_BEARER_TOKEN=${DEVELOPMENT_BEARER_TOKEN}
    depends_on:
      - eventstore
    restart: no
    tty: true
    ports:
      - "44001:44001"
    logging: *default-logging

  views:
    image: "kevinrutherford/rookery-views:local-dev"
    build:
      context: ${ROOKERY_VIEWS_REPO}
      dockerfile: dev.Dockerfile
    volumes:
      - ${ROOKERY_VIEWS_REPO}/src:/srv/app/src
    environment:
      - DEVELOPMENT_BEARER_TOKEN=${DEVELOPMENT_BEARER_TOKEN}
      - USER_1_ID=${USER_1_ID}
      - USER_1_USERNAME=${USER_1_USERNAME}
      - USER_1_DISPLAYNAME=${USER_1_DISPLAYNAME}
      - USER_1_AVATAR_URL=${USER_1_AVATAR_URL}
      - USER_2_ID=${USER_2_ID}
      - USER_2_USERNAME=${USER_2_USERNAME}
      - USER_2_DISPLAYNAME=${USER_2_DISPLAYNAME}
      - USER_2_AVATAR_URL=${USER_2_AVATAR_URL}
      - USER_3_ID=${USER_3_ID}
      - USER_3_USERNAME=${USER_3_USERNAME}
      - USER_3_DISPLAYNAME=${USER_3_DISPLAYNAME}
      - USER_3_AVATAR_URL=${USER_3_AVATAR_URL}
      - USER_CRB_ID=${USER_CRB_ID}
      - USER_CRB_USERNAME=${USER_CRB_USERNAME}
      - USER_CRB_DISPLAYNAME=${USER_CRB_DISPLAYNAME}
      - USER_CRB_AVATAR_URL=${USER_CRB_AVATAR_URL}
    depends_on:
      - eventstore
    restart: no
    tty: true
    ports:
      - "44002:44002"
    logging: *default-logging

  ui:
    image: "kevinrutherford/rookery-ui:local-dev"
    build:
      context: ${ROOKERY_UI_REPO}
      dockerfile: dev.Dockerfile
    volumes:
      - ${ROOKERY_UI_REPO}/app:/app/app
      - ${ROOKERY_UI_REPO}/public:/app/public
    depends_on:
      - commands
      - views
    restart: no
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - USER_1_ID=${USER_1_ID}
      - USER_1_USERNAME=${USER_1_USERNAME}
      - USER_2_ID=${USER_2_ID}
      - USER_2_USERNAME=${USER_2_USERNAME}
      - USER_3_ID=${USER_3_ID}
      - USER_3_USERNAME=${USER_3_USERNAME}
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    logging: *default-logging

  eventstore:
    image: eventstore/eventstore:lts
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:

